### ISSUE TITLE
IndexError: list index out of range?

### ISSUE THREAD

**Issue by mr-september** [medmaca/PGCNA#3]
Thanks for your help in the other issue, I've (probably) fixed my input file formats, and edited my running command.
Example input files for double-checking: 
[DEs_cluster_13.txt](https://github.com/medmaca/PGCNA/files/6068384/DEs_cluster_13.txt)
[#FileInfo.txt](https://github.com/medmaca/PGCNA/files/6068385/FileInfo.txt)

My terminal command:
```
python3 pgcna2.py -w <workdir> -d <inputdir> -f 1 --usePearson --noLeidenalg
```

And since I have ~60 input files, I'm just copy pasting the end of the outputs in terminal:

```
...
         DEg_cluster_14.txt     Reading expression data file: DEg_cluster_14.txt
                Total genes =  61
                # Generate Numpy matrices
                        Marix shape: (61, 46)
                # Generate gene meta information : done
                # Calculating correlations using HDF5 file to save memory
                        Creating HDF5 file
                        Calculating correlations for Chunk:
                         0
         DEg_cluster_15.txt     Reading expression data file: DEg_cluster_15.txt
                Total genes =  58
                # Generate Numpy matrices
                        Marix shape: (58, 23)
                # Generate gene meta information : done
                # Calculating correlations using HDF5 file to save memory
                        Creating HDF5 file
                        Calculating correlations for Chunk:
                         0
         DEs_cluster_0.txt      Reading expression data file: DEs_cluster_0.txt
                Total genes =  0
                # Generate Numpy matrices
Traceback (most recent call last):
  File "pgcna2.py", line 1133, in <module>
    main()
  File "pgcna2.py", line 1118, in main
    corrh5, genesM = generateCorrMatrix(OUT_FOLDER, metaInf, genesToKeep, requireFileNum, singleCorrList, geneFrac=args.geneFrac, retainF=args.retainF, corrMatF=args.corrMatF, corrMatFS=args.corrMatFS, usePearson=args.usePearson, corrChunk=args.corrChunk, splitBy=args.fileSep, 
  File "pgcna2.py", line 565, in generateCorrMatrix
    nrow = len(expression[0])
IndexError: list index out of range
```

How can I solve this part?

**Comment by medmaca** [comment]
It appears that DE_cluster_0.txt has an issue (can you share that file)

Also can you give me an overview of what you're trying to accomplish with this analysis?  What is your data, what do you want to do with it etc?

When you point pgcna2 at multiple files (e.g. #FileInfo.txt has multiple files), it calculates a correlation matrix for each of those files, and then combines the correlation matrices for shared genes to create the median correlation matrix.  This allows you to throw a number of related expression datasets (e.g. breast cancer expression datasets) and it will use them all to try to create a more refined gene correlation matrix, before commencing with edge trimming etc.  So it is expecting to combine the results, not produce results per file... if that makes sense?

**I realise, upon re-reading it, that I need to modify my README to make this fact clearer.  As it currently isn't**

**Comment by mr-september** [comment]
[DEs_cluster_0.txt](https://github.com/medmaca/PGCNA/files/6069295/DEs_cluster_0.txt)

I see... Hmm I am just trying to get some form of co-expression matrix for these genes in this cluster, and it doesn't have to be positive, negative, or even strongly co-expressed, even weak co-expression is a valid data point for my next steps.

Is it possible to run PGCNA without the combining steps, and just output separate co-expression matrix for each input file?

**Comment by medmaca** [comment]
So the problem with DEs_cluster_0.txt is that it contains genes with zero expression (all zeros).  If you remove these genes then it should work.  Again, pgcna2 wasn't designed for such sparse matrices.

You'd have to run pgcna2 with a different #Fileinfo.txt for each file... which isn't exactly ideal.  You might be better off calculating the correlations for each of these files yourself if that is all you need.  However, you probably want to look into methods for dealing with such sparse matrices (e.g. https://www.biorxiv.org/content/10.1101/2020.09.03.282178v1.full )

**Comment by mr-september** [comment]
You made a very good point there, it has slipped my mind that "DEs" sets are **intentionally** almost all zeros. In this case I think it would be meaningless to try and construct a network.
